eval.batch_size: 2
eval.cutoff_len: 1024
eval.dataset:
- sunxiaochuan
eval.dataset_dir: data
eval.max_new_tokens: 512
eval.max_samples: '500'
eval.output_dir: eval_2025-03-06-08-28-01
eval.predict: true
eval.temperature: 1.1
eval.top_p: 0.7
top.booster: auto
top.checkpoint_path:
- normal_gpt
top.finetuning_type: lora
top.model_name: Qwen2.5-3B-Instruct
top.quantization_bit: none
top.quantization_method: bitsandbytes
top.rope_scaling: none
top.template: qwen
