adapter_name_or_path: saves/Qwen2.5-3B-Instruct/lora/normal_gpt
cutoff_len: 1024
dataset_dir: data
do_predict: true
eval_dataset: sunxiaochuan
finetuning_type: lora
flash_attn: auto
max_new_tokens: 512
max_samples: 500
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
output_dir: saves/Qwen2.5-3B-Instruct/lora/eval_2025-03-06-08-28-01
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bitsandbytes
stage: sft
temperature: 1.1
template: qwen
top_p: 0.7
trust_remote_code: true
